#
# ini file of runmapextr.sh script
#
# Work directory
# ==============
ANA_WORKDIR="/work/cmcc/ag15419/OUTPUT_QUID/HA/area_EAS9_2017/"

# Start and end date ( format YYYYMMDD )
# =====================================
ANA_STARTDATE=20170701
ANA_ENDDATE=20171231

# NEMO outputs path and file name template 
# =========================================

# WARNING: choose one dataset per run
# WARNING: Date in the file name MUST be replaced by the following string: %YYYYMMDD% 
# WARNING: file are supposed to be stored in daily directories $ANA_INPATHS/$DATE/model/$ANA_INFILES, if not change line of the job 
ANA_INPATHS=("/work/cmcc/mfs-dev/medfs/fix_mfseas9_longrun/EXP00/")
ANA_INFILES_TPL=("medfs-eas9_1h_%YYYYMMDD%_2D_grid_T.nc")
# name of the exp:
# WARNING: this name is used also form the fit and analysis/plot scripts,
#          so, if you change it, you should also modify it in the other scripts accordingly
ANA_INTAG=( "medfs-eas9" )

# Job vars 
#==========
# Job name
J_NAME='SSH_a_extr' 
# Job out and err paths
J_OUT="$ANA_WORKDIR/extr_%J.out" 
J_ERR="$ANA_WORKDIR/extr_%J.err"
# Job queue
J_QUEUE='s_long'
# Job resources
J_CPUS='1'
# Project number
J_PROJ='0510'
# Job memory
J_MEM="20G"

###########################################################
# DO NOT CHANGE THE CODE BELOW THIS LINES
###########################################################

# MODEL INFOS 
# ============== 
# To activate map extraction set the following flag to 1
MAP_FLAG=1
# Select the grid
GRID_TO_EXTRACT="T"

# Field name and units
if [[ $GRID_TO_EXTRACT == "T" ]]; then
   # grid_T files
   # 3D FIELDS
   VAR3D_NAME="" 
   VAR3D_UDM=""
   # 2D FIELDS
   VAR2D_NAME=( "sossheig") 
   VAR2D_UDM=( "m" ) 

elif [[ $GRID_TO_EXTRACT == "uv2t" ]]; then
   # grid_uv2t files
   # 3D FIELDS
   VAR3D_NAME=( "i" ) 
   VAR3D_UDM=( "m/s" ) 

elif [[ $GRID_TO_EXTRACT == "U" ]]; then
     # grid_U files
     # 3D FIELDS
     VAR3D_NAME=""
     VAR3D_UDM=""
     # 2D FIELDS
     VAR2D_NAME=( "sozotaux" )
     VAR2D_UDM=( "N/m2" )

elif [[ $GRID_TO_EXTRACT == "V" ]]; then
     # grid_V files
     # 3D FIELDS
     VAR3D_NAME=""
     VAR3D_UDM=""
     # 2D FIELDS
     VAR2D_NAME=( "sometauy" )
     VAR2D_UDM=( "N/m2" )
fi


# Outputs
# =================================================
# Name of extracted files
MAP3D_OUTFILE_TPL="map3D_%LEV%_%FIELD%_%ANA_STARTDATE%_%ANA_ENDDATE%_mod_%INDATASET%.nc" # All time-steps
MAP2D_OUTFILE_TPL="map2D_0_%FIELD%_%ANA_STARTDATE%_%ANA_ENDDATE%_mod_%INDATASET%.nc" # All time-steps

# Name of the file template that will be used from the fit script to built the harmonic analysis output file..
AMPPHA_NEWFILE_TPL="amppha2D_0_%FIELD%_%ANA_STARTDATE%_%ANA_ENDDATE%_mod_%INDATASET%.nc"

# Environment
#=================================================
MAP_MODULE="intel-2021.6.0/netcdf-c-threadsafe/4.9.0-25h5k  intel-2021.6.0/cdo-threadsafe/2.1.1-lyjsw  intel-2021.6.0/nco/5.0.6-jp6y4  intel-2021.6.0/ncview/2.1.8-sds5t  intel-2021.6.0/netcdf-c/4.9.0-cjqig  intel-2021.6.0/cdo-threadsafe/2.1.1-lyjsw  intel-2021.6.0/imagemagick/7.0.8-7-2475g   anaconda/3-2022.10"

